module.exports.title = [
    '꾸에바마테라(Cueva Matera)',
    '겟댓샷(Get that Shot)',
    '(hiD)',
    '943킹스크로스(943 Kings Cross Harry Potter)',
    '스타일난다 핑크풀카페(Style Nanda Pink Pool)',
    '바나나트리 성수점(Banana Tree)',
    '또옹카페(Ddo-ong)',
    '오리올케이크(Oriole)',
    '브레댄코 영옹구읍뱃터짐(Bread&co)',
    '호호미욜(hoho Myoll)',
    '채널플라스틱(Channel Plastic)',
    '트룰리베이커(Truly Baker)',
    '스타벅스 경주대릉원점(Starbucks-Gyeongju)',
    '채그로(The Cheagulo)',
    '땡스오트 안국(Thanks, Oat)',
    '메그네이트(Magnate)',
    '젬스톤(Gemstone)',
    '보사노바 커피로스터스(Bossa Nova)',
    '메인스트리트(Main Street)',
    '해피베어데이 본점(Happy Bear Day)',
    '땡스네이쳐카페(Thanks Nature Cafe)',
    '카페인(Cafe In)',
    '도산맘마미아(Mammamia)',
    '카페하이클래스(High Class 153)',
    '달빛여수(Moonlight)',
    '카페 라피끄(Rafik)',
    '카페드몽돌(Cafe de Mongdol)',
    '청수당한밭(Cheongsudang Hanbat)',
    '카페포토피아(Cafe Fotopia)',
    '스타벅스 제주중문점(Starbucks-Jeju)',
    '엘라사(Elisha)',
    '델문도(Cafe Delmoondo)',
    '공간태리(Teri)',
    '에이트(Eight)'
]